name: Manual lessons trigger
on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'type smt and press enter'
        required: false
        type: number
   
jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Run DuoXPy
        run: python bot.py
